# University URLs to scrape
UNIVERSITY_URLS = [
    'https://jinnah.edu/',
    'https://jinnah.edu/chancellor-message/',
    'https://jinnah.edu/presidents-message/',
    'https://jinnah.edu/about-maju/',
    'https://jinnah.edu/my-maju/allpolicy/undergraduate-regulations/',
    'https://jinnah.edu/my-maju/allpolicy/phd-regulations/',
    'https://jinnah.edu/my-maju/allpolicy/general-policies/',
    'https://jinnah.edu/my-maju/allpolicy/university-dress-code/',
    'https://jinnah.edu/my-maju/academic-calendar/',
    'https://jinnah.edu/faculty-of-engineering/',
    'https://jinnah.edu/faculty-of-computing/',
    'https://jinnah.edu/faculty-of-business-administration/',
    'https://jinnah.edu/faculty-of-social-and-basic-sciences/',
    'https://jinnah.edu/faculty-of-life-sciences/',
    'https://jinnah.edu/faculty-of-engineering/department-of-electrical-engineering/',
    'https://jinnah.edu/faculty-of-computing/department-of-computer-science/',
    'https://jinnah.edu/faculty-of-business-administration/department-of-business-administration/',
    'https://jinnah.edu/faculty-of-social-and-basic-sciences/department-of-psychology/',
    'https://jinnah.edu/faculty-of-social-and-basic-sciences/department-of-social-sciences/',
    'https://jinnah.edu/faculty-of-life-sciences/department-of-bio-sciences/',
    'https://jinnah.edu/blog/',
    'https://jinnah.edu/key-admission-dates/',
    'https://jinnah.edu/composition-of-admission-test/',
    'https://jinnah.edu/fee-structure-scholarship/',
    'https://jinnah.edu/eligibility-criteria/',
    'https://jinnah.edu/admissions/how-to-apply-for-admissions/',
    'https://jinnah.edu/key-points-for-foreign-admissions/',
    'https://jinnah.edu/merit-list-preparation/',
    'https://jinnah.edu/sample-papers/',
    'https://jinnah.edu/faqs/',
    'https://jinnah.edu/scholarship/',
    'https://jinnah.edu/undergraduate-programs/',
    'https://jinnah.edu/2-year-undergraduate-programs/',
    'https://jinnah.edu/graduate-programs/',
    'https://jinnah.edu/doctorate-programs/',
    'https://jinnah.edu/engineering-program/',
    'https://jinnah.edu/computing-program/',
    'https://jinnah.edu/business-administration-and-social-sciences-programs/',
    'https://jinnah.edu/oric/',
    'https://jinnah.edu/oric/industrial-collaborations/',
    'https://jinnah.edu/oric/publications/',
    'https://jinnah.edu/qec/',
    'https://jinnah.edu/message-by-the-director-qec/',
    'https://jinnah.edu/vision-and-mission/',
    'https://jinnah.edu/qec_aims/',
    'https://jinnah.edu/organogram/',
    'https://jinnah.edu/qac-members/',
    'https://jinnah.edu/external-linkages/',
    'https://jinnah.edu/placement-office/',
    'https://jinnah.edu/my-maju/vis-directorate/',
    'https://jinnah.edu/about-dse/',
]

# Vector DB Configuration
VECTOR_DB_CONFIG = {
    'index_path': 'vector_db/faiss_index',
    'embedding_model': 'all-MiniLM-L6-v2',
    'chunk_size': 1000,
    'chunk_overlap': 200
}